
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Apr 16 2026 13:53:01 IST (Apr 16 2026 08:23:01 UTC)

// Verification Directory fv/pe64_top 

module pe64_top(clk, rst_n, enable, d, q, v, scan_en, scan_in,
     scan_out);
  input clk, rst_n, enable, scan_en, scan_in;
  input [63:0] d;
  output [5:0] q;
  output v, scan_out;
  wire clk, rst_n, enable, scan_en, scan_in;
  wire [63:0] d;
  wire [5:0] q;
  wire v, scan_out;
  wire [63:0] d_s1;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire en_s1, n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  wire n_7, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_15, n_16, n_17, n_18, n_19, n_20, n_21, n_22;
  wire n_23, n_24, n_25, n_26, n_27, n_28, n_29, n_30;
  wire n_31, n_32, n_33, n_34, n_35, n_36, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_56, n_57, n_58, n_59, n_60, n_61, n_62;
  wire n_63, n_64, n_65, n_66, n_67, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_101, n_102;
  wire n_103, n_104, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_125, n_126;
  wire n_127, n_128, n_129, n_130;
  assign scan_out = 1'b0;
  DFFQXL \q_reg[0] (.CK (clk), .D (n_130), .Q (q[0]));
  AOI21XL g3237__2398(.A0 (n_41), .A1 (n_127), .B0 (n_128), .Y (n_130));
  DFFQXL \q_reg[1] (.CK (clk), .D (n_129), .Q (q[1]));
  AOI21XL g3239__5107(.A0 (n_40), .A1 (n_126), .B0 (n_128), .Y (n_129));
  OAI21XL g3240__6260(.A0 (n_123), .A1 (n_125), .B0 (n_124), .Y
       (n_127));
  OAI21XL g3241__4319(.A0 (n_122), .A1 (n_125), .B0 (n_124), .Y
       (n_126));
  AOI31XL g3242__8428(.A0 (n_117), .A1 (n_54), .A2 (d_s1[61]), .B0
       (n_122), .Y (n_123));
  NAND3XL g3243__5526(.A (d_s1[62]), .B (n_61), .C (n_121), .Y (n_122));
  NAND3XL g3244__6783(.A (d_s1[63]), .B (n_59), .C (n_120), .Y (n_125));
  AOI221XL g3245__3680(.A0 (d_s1[54]), .A1 (n_119), .B0 (d_s1[42]), .B1
       (n_118), .C0 (n_115), .Y (n_121));
  AOI221XL g3246__1617(.A0 (d_s1[55]), .A1 (n_119), .B0 (d_s1[43]), .B1
       (n_118), .C0 (n_113), .Y (n_120));
  AOI221XL g3247__2802(.A0 (d_s1[45]), .A1 (n_60), .B0 (d_s1[41]), .B1
       (n_118), .C0 (n_116), .Y (n_117));
  OAI211XL g3250__1705(.A0 (n_114), .A1 (d_s1[29]), .B0 (n_99), .C0
       (n_110), .Y (n_116));
  OAI211XL g3251__5122(.A0 (n_114), .A1 (d_s1[30]), .B0 (n_98), .C0
       (n_107), .Y (n_115));
  OAI211XL g3252__8246(.A0 (n_114), .A1 (d_s1[31]), .B0 (n_95), .C0
       (n_111), .Y (n_113));
  DFFQXL \q_reg[2] (.CK (clk), .D (n_112), .Q (q[2]));
  AOI21XL g3249__7098(.A0 (n_43), .A1 (n_105), .B0 (n_128), .Y (n_112));
  DFFQXL \q_reg[3] (.CK (clk), .D (n_106), .Q (q[3]));
  AOI221XL g3255__6131(.A0 (d_s1[35]), .A1 (n_109), .B0 (d_s1[23]), .B1
       (n_108), .C0 (n_104), .Y (n_111));
  AOI221XL g3256__1881(.A0 (d_s1[33]), .A1 (n_109), .B0 (d_s1[21]), .B1
       (n_108), .C0 (n_103), .Y (n_110));
  AOI221XL g3257__5115(.A0 (d_s1[34]), .A1 (n_109), .B0 (d_s1[22]), .B1
       (n_108), .C0 (n_100), .Y (n_107));
  AOI21XL g3254__7482(.A0 (n_42), .A1 (n_94), .B0 (n_128), .Y (n_106));
  OAI21XL g3258__4733(.A0 (n_87), .A1 (n_93), .B0 (n_124), .Y (n_105));
  OAI221XL g3259__6161(.A0 (d_s1[27]), .A1 (n_102), .B0 (d_s1[39]), .B1
       (n_101), .C0 (n_88), .Y (n_104));
  OAI221XL g3260__9315(.A0 (d_s1[25]), .A1 (n_102), .B0 (d_s1[37]), .B1
       (n_101), .C0 (n_91), .Y (n_103));
  OAI221XL g3261__9945(.A0 (d_s1[26]), .A1 (n_102), .B0 (d_s1[38]), .B1
       (n_101), .C0 (n_92), .Y (n_100));
  AOI22XL g3263__2883(.A0 (n_97), .A1 (d_s1[1]), .B0 (n_96), .B1
       (d_s1[57]), .Y (n_99));
  AOI22XL g3264__2346(.A0 (n_97), .A1 (d_s1[2]), .B0 (n_96), .B1
       (d_s1[58]), .Y (n_98));
  AOI22XL g3265__1666(.A0 (n_97), .A1 (d_s1[3]), .B0 (n_96), .B1
       (d_s1[59]), .Y (n_95));
  OAI21XL g3262__7410(.A0 (n_86), .A1 (n_93), .B0 (n_124), .Y (n_94));
  AOI221XL g3266__6417(.A0 (d_s1[6]), .A1 (n_90), .B0 (d_s1[10]), .B1
       (n_89), .C0 (n_85), .Y (n_92));
  AOI221XL g3267__5477(.A0 (d_s1[5]), .A1 (n_90), .B0 (d_s1[9]), .B1
       (n_89), .C0 (n_81), .Y (n_91));
  AOI221XL g3268__2398(.A0 (d_s1[7]), .A1 (n_90), .B0 (d_s1[11]), .B1
       (n_89), .C0 (n_84), .Y (n_88));
  AOI21XL g3269__5107(.A0 (n_50), .A1 (n_74), .B0 (n_86), .Y (n_87));
  NOR2BXL g3274__6260(.AN (n_90), .B (n_73), .Y (n_97));
  NAND2XL g3270__4319(.A (n_96), .B (n_80), .Y (n_93));
  NAND2XL g3271__8428(.A (n_48), .B (n_78), .Y (n_86));
  OAI22XL g3277__5526(.A0 (n_83), .A1 (d_s1[14]), .B0 (n_82), .B1
       (d_s1[18]), .Y (n_85));
  OAI22XL g3272__6783(.A0 (n_83), .A1 (d_s1[15]), .B0 (n_82), .B1
       (d_s1[19]), .Y (n_84));
  OAI22XL g3273__3680(.A0 (n_83), .A1 (d_s1[13]), .B0 (n_82), .B1
       (d_s1[17]), .Y (n_81));
  NOR2XL g3279__1617(.A (n_79), .B (n_83), .Y (n_89));
  NOR2XL g3280__2802(.A (n_52), .B (n_83), .Y (n_90));
  AOI222XL g3276__1705(.A0 (n_56), .A1 (n_77), .B0 (n_64), .B1 (n_76),
       .C0 (n_75), .C1 (n_79), .Y (n_80));
  AOI222XL g3278__5122(.A0 (n_63), .A1 (n_77), .B0 (n_69), .B1 (n_76),
       .C0 (n_75), .C1 (n_47), .Y (n_78));
  AOI222XL g3275__8246(.A0 (n_65), .A1 (n_77), .B0 (n_72), .B1 (n_76),
       .C0 (n_75), .C1 (n_73), .Y (n_74));
  INVXL g3285(.A (n_75), .Y (n_83));
  NOR2XL g3287__7098(.A (n_49), .B (n_82), .Y (n_75));
  NAND2BXL g3290__6131(.AN (n_72), .B (n_108), .Y (n_82));
  DFFQXL \q_reg[5] (.CK (clk), .D (n_70), .Q (q[5]));
  DFFQXL \q_reg[4] (.CK (clk), .D (n_71), .Q (q[4]));
  DFFQXL v_reg(.CK (clk), .D (n_68), .Q (v));
  NOR2XL g3284__1881(.A (n_66), .B (n_128), .Y (n_71));
  NOR2XL g3288__5115(.A (n_67), .B (n_128), .Y (n_70));
  NOR2XL g3294__7482(.A (n_69), .B (n_102), .Y (n_108));
  AOI211XL g3283__4733(.A0 (n_53), .A1 (n_76), .B0 (en_s1), .C0
       (n_128), .Y (n_68));
  AOI22XL g3291__6161(.A0 (n_114), .A1 (n_124), .B0 (q[5]), .B1
       (en_s1), .Y (n_67));
  AOI21XL g3289__9315(.A0 (en_s1), .A1 (q[4]), .B0 (n_62), .Y (n_66));
  NOR2XL g3292__9945(.A (n_65), .B (n_101), .Y (n_109));
  NAND2BXL g3296__2883(.AN (n_64), .B (n_76), .Y (n_102));
  NAND2BXL g3297__2346(.AN (n_63), .B (n_118), .Y (n_101));
  INVXL g3302(.A (n_114), .Y (n_76));
  NOR2XL g3293__1666(.A (en_s1), .B (n_77), .Y (n_62));
  AOI22XL g3295__7410(.A0 (n_60), .A1 (d_s1[46]), .B0 (n_58), .B1
       (d_s1[50]), .Y (n_61));
  AOI22XL g3298__6417(.A0 (n_60), .A1 (d_s1[47]), .B0 (n_58), .B1
       (d_s1[51]), .Y (n_59));
  NAND2XL g3304__5477(.A (n_57), .B (n_60), .Y (n_114));
  AOI21XL g3300__2398(.A0 (n_51), .A1 (n_57), .B0 (n_55), .Y (n_77));
  NOR2XL g3301__5107(.A (n_56), .B (n_55), .Y (n_118));
  INVXL g3305(.A (n_55), .Y (n_60));
  AOI22XL g3303__6260(.A0 (n_58), .A1 (d_s1[49]), .B0 (n_119), .B1
       (d_s1[53]), .Y (n_54));
  NAND2XL g3306__4319(.A (n_44), .B (n_58), .Y (n_55));
  NOR4XL g3299__8428(.A (n_46), .B (n_73), .C (n_52), .D (n_51), .Y
       (n_53));
  AND2XL g3309__5526(.A (n_50), .B (n_119), .Y (n_58));
  OR4XL g3307__6783(.A (n_64), .B (n_72), .C (n_69), .D (n_49), .Y
       (n_51));
  NOR4XL g3308__3680(.A (n_45), .B (n_56), .C (n_63), .D (n_65), .Y
       (n_57));
  AND2XL g3310__1617(.A (n_48), .B (n_96), .Y (n_119));
  OR2XL g3311__2802(.A (n_79), .B (n_47), .Y (n_52));
  OR4XL g3313__1705(.A (d_s1[0]), .B (d_s1[3]), .C (d_s1[2]), .D
       (d_s1[1]), .Y (n_46));
  OR4XL g3312__5122(.A (d_s1[32]), .B (d_s1[35]), .C (d_s1[34]), .D
       (d_s1[33]), .Y (n_45));
  OR4XL g3321__8246(.A (d_s1[8]), .B (d_s1[9]), .C (d_s1[10]), .D
       (d_s1[11]), .Y (n_47));
  OR4XL g3316__7098(.A (d_s1[40]), .B (d_s1[41]), .C (d_s1[42]), .D
       (d_s1[43]), .Y (n_63));
  OR4XL g3324__6131(.A (d_s1[44]), .B (d_s1[45]), .C (d_s1[46]), .D
       (d_s1[47]), .Y (n_56));
  NOR4XL g3320__1881(.A (d_s1[48]), .B (d_s1[51]), .C (d_s1[50]), .D
       (d_s1[49]), .Y (n_44));
  NOR4XL g3323__5115(.A (d_s1[56]), .B (d_s1[57]), .C (d_s1[58]), .D
       (d_s1[59]), .Y (n_48));
  NOR4XL g3322__7482(.A (d_s1[52]), .B (d_s1[53]), .C (d_s1[54]), .D
       (d_s1[55]), .Y (n_50));
  OR4XL g3325__4733(.A (d_s1[4]), .B (d_s1[5]), .C (d_s1[6]), .D
       (d_s1[7]), .Y (n_73));
  OR4XL g3319__6161(.A (d_s1[20]), .B (d_s1[21]), .C (d_s1[22]), .D
       (d_s1[23]), .Y (n_72));
  NAND4XL g3314__9315(.A (d_s1[16]), .B (d_s1[17]), .C (d_s1[18]), .D
       (d_s1[19]), .Y (n_49));
  NAND4XL g3315__9945(.A (d_s1[28]), .B (d_s1[29]), .C (d_s1[30]), .D
       (d_s1[31]), .Y (n_64));
  AND4XL g3327__2883(.A (d_s1[60]), .B (d_s1[61]), .C (d_s1[62]), .D
       (d_s1[63]), .Y (n_96));
  NAND4XL g3317__2346(.A (d_s1[36]), .B (d_s1[37]), .C (d_s1[38]), .D
       (d_s1[39]), .Y (n_65));
  NAND4XL g3326__1666(.A (d_s1[12]), .B (d_s1[13]), .C (d_s1[14]), .D
       (d_s1[15]), .Y (n_79));
  NAND4XL g3318__7410(.A (d_s1[24]), .B (d_s1[25]), .C (d_s1[26]), .D
       (d_s1[27]), .Y (n_69));
  DFFQXL \d_s1_reg[40] (.CK (clk), .D (n_30), .Q (d_s1[40]));
  NAND2XL g3330__6417(.A (en_s1), .B (q[2]), .Y (n_43));
  NAND2XL g3331__5477(.A (en_s1), .B (q[3]), .Y (n_42));
  DFFQXL \d_s1_reg[44] (.CK (clk), .D (n_13), .Q (d_s1[44]));
  NAND2XL g3329__2398(.A (en_s1), .B (q[0]), .Y (n_41));
  DFFQXL \d_s1_reg[0] (.CK (clk), .D (n_34), .Q (d_s1[0]));
  DFFQXL \d_s1_reg[32] (.CK (clk), .D (n_14), .Q (d_s1[32]));
  NAND2XL g3328__5107(.A (en_s1), .B (q[1]), .Y (n_40));
  DFFQXL \d_s1_reg[41] (.CK (clk), .D (n_37), .Q (d_s1[41]));
  DFFQXL \d_s1_reg[33] (.CK (clk), .D (n_35), .Q (d_s1[33]));
  DFFQXL \d_s1_reg[34] (.CK (clk), .D (n_32), .Q (d_s1[34]));
  DFFQXL \d_s1_reg[35] (.CK (clk), .D (n_31), .Q (d_s1[35]));
  DFFQXL \d_s1_reg[22] (.CK (clk), .D (n_6), .Q (d_s1[22]));
  DFFQXL \d_s1_reg[51] (.CK (clk), .D (n_39), .Q (d_s1[51]));
  DFFQXL \d_s1_reg[53] (.CK (clk), .D (n_0), .Q (d_s1[53]));
  DFFQXL \d_s1_reg[2] (.CK (clk), .D (n_25), .Q (d_s1[2]));
  DFFQXL \d_s1_reg[43] (.CK (clk), .D (n_26), .Q (d_s1[43]));
  DFFQXL \d_s1_reg[3] (.CK (clk), .D (n_3), .Q (d_s1[3]));
  DFFQXL \d_s1_reg[45] (.CK (clk), .D (n_8), .Q (d_s1[45]));
  DFFQXL \d_s1_reg[58] (.CK (clk), .D (n_4), .Q (d_s1[58]));
  DFFQXL \d_s1_reg[46] (.CK (clk), .D (n_15), .Q (d_s1[46]));
  DFFQXL \d_s1_reg[47] (.CK (clk), .D (n_16), .Q (d_s1[47]));
  DFFQXL \d_s1_reg[56] (.CK (clk), .D (n_23), .Q (d_s1[56]));
  DFFQXL \d_s1_reg[4] (.CK (clk), .D (n_24), .Q (d_s1[4]));
  DFFQXL \d_s1_reg[48] (.CK (clk), .D (n_19), .Q (d_s1[48]));
  DFFQXL \d_s1_reg[20] (.CK (clk), .D (n_18), .Q (d_s1[20]));
  DFFQXL \d_s1_reg[52] (.CK (clk), .D (n_22), .Q (d_s1[52]));
  DFFQXL \d_s1_reg[8] (.CK (clk), .D (n_2), .Q (d_s1[8]));
  DFFQXL \d_s1_reg[9] (.CK (clk), .D (n_10), .Q (d_s1[9]));
  DFFQXL \d_s1_reg[11] (.CK (clk), .D (n_28), .Q (d_s1[11]));
  DFFQXL \d_s1_reg[59] (.CK (clk), .D (n_20), .Q (d_s1[59]));
  DFFQXL \d_s1_reg[10] (.CK (clk), .D (n_1), .Q (d_s1[10]));
  DFFQXL \d_s1_reg[42] (.CK (clk), .D (n_33), .Q (d_s1[42]));
  DFFQXL \d_s1_reg[1] (.CK (clk), .D (n_12), .Q (d_s1[1]));
  DFFQXL \d_s1_reg[6] (.CK (clk), .D (n_38), .Q (d_s1[6]));
  DFFQXL \d_s1_reg[57] (.CK (clk), .D (n_11), .Q (d_s1[57]));
  DFFQXL \d_s1_reg[7] (.CK (clk), .D (n_7), .Q (d_s1[7]));
  DFFQXL \d_s1_reg[54] (.CK (clk), .D (n_36), .Q (d_s1[54]));
  DFFQXL \d_s1_reg[21] (.CK (clk), .D (n_27), .Q (d_s1[21]));
  DFFQXL \d_s1_reg[49] (.CK (clk), .D (n_17), .Q (d_s1[49]));
  DFFQXL \d_s1_reg[23] (.CK (clk), .D (n_29), .Q (d_s1[23]));
  DFFQXL \d_s1_reg[55] (.CK (clk), .D (n_5), .Q (d_s1[55]));
  DFFQXL \d_s1_reg[5] (.CK (clk), .D (n_21), .Q (d_s1[5]));
  DFFQXL \d_s1_reg[50] (.CK (clk), .D (n_9), .Q (d_s1[50]));
  NOR2BXL g3411__6260(.AN (d[51]), .B (n_128), .Y (n_39));
  NOR2BXL g3430__4319(.AN (d[6]), .B (n_128), .Y (n_38));
  NOR2BXL g3431__8428(.AN (d[41]), .B (n_128), .Y (n_37));
  NOR2BXL g3398__5526(.AN (d[54]), .B (n_128), .Y (n_36));
  NOR2BXL g3400__6783(.AN (d[33]), .B (n_128), .Y (n_35));
  NOR2BXL g3401__3680(.AN (d[0]), .B (n_128), .Y (n_34));
  NOR2BXL g3402__1617(.AN (d[42]), .B (n_128), .Y (n_33));
  NOR2BXL g3403__2802(.AN (d[34]), .B (n_128), .Y (n_32));
  NOR2BXL g3404__1705(.AN (d[35]), .B (n_128), .Y (n_31));
  NOR2BXL g3405__5122(.AN (d[40]), .B (n_128), .Y (n_30));
  NOR2BXL g3436__8246(.AN (d[23]), .B (n_128), .Y (n_29));
  NOR2BXL g3406__7098(.AN (d[11]), .B (n_128), .Y (n_28));
  NOR2BXL g3407__6131(.AN (d[21]), .B (n_128), .Y (n_27));
  NOR2BXL g3408__1881(.AN (d[43]), .B (n_128), .Y (n_26));
  NOR2BXL g3409__5115(.AN (d[2]), .B (n_128), .Y (n_25));
  NOR2BXL g3410__7482(.AN (d[4]), .B (n_128), .Y (n_24));
  NOR2BXL g3428__4733(.AN (d[56]), .B (n_128), .Y (n_23));
  NOR2BXL g3413__6161(.AN (d[52]), .B (n_128), .Y (n_22));
  NOR2BXL g3414__9315(.AN (d[5]), .B (n_128), .Y (n_21));
  NOR2BXL g3435__9945(.AN (d[59]), .B (n_128), .Y (n_20));
  NOR2BXL g3415__2883(.AN (d[48]), .B (n_128), .Y (n_19));
  NOR2BXL g3434__2346(.AN (d[20]), .B (n_128), .Y (n_18));
  NOR2BXL g3417__1666(.AN (d[49]), .B (n_128), .Y (n_17));
  NOR2BXL g3418__7410(.AN (d[47]), .B (n_128), .Y (n_16));
  NOR2BXL g3419__6417(.AN (d[46]), .B (n_128), .Y (n_15));
  NOR2BXL g3432__5477(.AN (d[32]), .B (n_128), .Y (n_14));
  NOR2BXL g3421__2398(.AN (d[44]), .B (n_128), .Y (n_13));
  NOR2BXL g3422__5107(.AN (d[1]), .B (n_128), .Y (n_12));
  NOR2BXL g3423__6260(.AN (d[57]), .B (n_128), .Y (n_11));
  NOR2BXL g3426__4319(.AN (d[9]), .B (n_128), .Y (n_10));
  NOR2BXL g3425__8428(.AN (d[50]), .B (n_128), .Y (n_9));
  NOR2BXL g3429__5526(.AN (d[45]), .B (n_128), .Y (n_8));
  DFFTRXL \d_s1_reg[28] (.CK (clk), .D (d[28]), .RN (rst_n), .Q
       (UNCONNECTED), .QN (d_s1[28]));
  NOR2BXL g3424__6783(.AN (d[7]), .B (n_128), .Y (n_7));
  NOR2BXL g3433__3680(.AN (d[22]), .B (n_128), .Y (n_6));
  NOR2BXL g3399__1617(.AN (d[55]), .B (n_128), .Y (n_5));
  NOR2BXL g3437__2802(.AN (d[58]), .B (n_128), .Y (n_4));
  NOR2BXL g3412__1705(.AN (d[3]), .B (n_128), .Y (n_3));
  NOR2BXL g3427__5122(.AN (d[8]), .B (n_128), .Y (n_2));
  DFFTRXL \d_s1_reg[36] (.CK (clk), .D (d[36]), .RN (rst_n), .Q
       (UNCONNECTED0), .QN (d_s1[36]));
  DFFTRXL \d_s1_reg[60] (.CK (clk), .D (d[60]), .RN (rst_n), .Q
       (UNCONNECTED1), .QN (d_s1[60]));
  NOR2BXL g3416__8246(.AN (d[10]), .B (n_128), .Y (n_1));
  DFFTRXL \d_s1_reg[24] (.CK (clk), .D (d[24]), .RN (rst_n), .Q
       (UNCONNECTED2), .QN (d_s1[24]));
  DFFTRXL \d_s1_reg[16] (.CK (clk), .D (d[16]), .RN (rst_n), .Q
       (UNCONNECTED3), .QN (d_s1[16]));
  DFFTRXL \d_s1_reg[12] (.CK (clk), .D (d[12]), .RN (rst_n), .Q
       (UNCONNECTED4), .QN (d_s1[12]));
  NOR2BXL g3420__7098(.AN (d[53]), .B (n_128), .Y (n_0));
  DFFTRXL \d_s1_reg[19] (.CK (clk), .D (d[19]), .RN (rst_n), .Q
       (UNCONNECTED5), .QN (d_s1[19]));
  DFFTRXL \d_s1_reg[62] (.CK (clk), .D (d[62]), .RN (rst_n), .Q
       (UNCONNECTED6), .QN (d_s1[62]));
  DFFTRXL \d_s1_reg[14] (.CK (clk), .D (d[14]), .RN (rst_n), .Q
       (UNCONNECTED7), .QN (d_s1[14]));
  DFFTRXL \d_s1_reg[18] (.CK (clk), .D (d[18]), .RN (rst_n), .Q
       (UNCONNECTED8), .QN (d_s1[18]));
  DFFTRXL \d_s1_reg[15] (.CK (clk), .D (d[15]), .RN (rst_n), .Q
       (UNCONNECTED9), .QN (d_s1[15]));
  DFFTRXL \d_s1_reg[63] (.CK (clk), .D (d[63]), .RN (rst_n), .Q
       (UNCONNECTED10), .QN (d_s1[63]));
  DFFTRXL \d_s1_reg[17] (.CK (clk), .D (d[17]), .RN (rst_n), .Q
       (UNCONNECTED11), .QN (d_s1[17]));
  DFFTRXL \d_s1_reg[38] (.CK (clk), .D (d[38]), .RN (rst_n), .Q
       (UNCONNECTED12), .QN (d_s1[38]));
  DFFTRXL \d_s1_reg[30] (.CK (clk), .D (d[30]), .RN (rst_n), .Q
       (UNCONNECTED13), .QN (d_s1[30]));
  DFFTRXL \d_s1_reg[26] (.CK (clk), .D (d[26]), .RN (rst_n), .Q
       (UNCONNECTED14), .QN (d_s1[26]));
  DFFTRXL \d_s1_reg[13] (.CK (clk), .D (d[13]), .RN (rst_n), .Q
       (UNCONNECTED15), .QN (d_s1[13]));
  DFFTRXL \d_s1_reg[27] (.CK (clk), .D (d[27]), .RN (rst_n), .Q
       (UNCONNECTED16), .QN (d_s1[27]));
  DFFTRXL \d_s1_reg[25] (.CK (clk), .D (d[25]), .RN (rst_n), .Q
       (UNCONNECTED17), .QN (d_s1[25]));
  DFFTRXL \d_s1_reg[39] (.CK (clk), .D (d[39]), .RN (rst_n), .Q
       (UNCONNECTED18), .QN (d_s1[39]));
  DFFTRXL \d_s1_reg[29] (.CK (clk), .D (d[29]), .RN (rst_n), .Q
       (UNCONNECTED19), .QN (d_s1[29]));
  DFFTRXL \d_s1_reg[37] (.CK (clk), .D (d[37]), .RN (rst_n), .Q
       (UNCONNECTED20), .QN (d_s1[37]));
  DFFTRXL \d_s1_reg[31] (.CK (clk), .D (d[31]), .RN (rst_n), .Q
       (UNCONNECTED21), .QN (d_s1[31]));
  DFFTRXL \d_s1_reg[61] (.CK (clk), .D (d[61]), .RN (rst_n), .Q
       (UNCONNECTED22), .QN (d_s1[61]));
  DFFTRXL en_s1_reg(.CK (clk), .D (enable), .RN (rst_n), .Q (n_124),
       .QN (en_s1));
  INVXL g3438(.A (rst_n), .Y (n_128));
endmodule

